
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 15 18:25:35 CEST 2013
//----------------------------------------------------

package tp2compile;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int UMINUS = 12;
  public static final int MOD = 7;
  public static final int SEMI = 2;
  public static final int BEGINAFF = 10;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int ENTIER = 13;
  public static final int ID = 14;
  public static final int error = 1;
  public static final int PAR_G = 8;
  public static final int TIMES = 5;
  public static final int SELECTAFF = 11;
  public static final int PAR_D = 9;
}

